apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-app
  labels: 
    app: photo-app
    
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: photo-app

  template:
    metadata: 
      matchLabels:
        app: photo-app
    spec:
      containers:
      - name: photo
        image: vignesh8386/photostudio:v1.0.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
          name: config
    
