apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-app
  labels: 
    app: photo-app
    
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: photo-app

  template:
    metadata: 
      labels:
        app: photo-app
    spec:
      containers:
      - name: photo
        image: vignesh8386/photostudio:v1.0.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: photo
        
---
apiVersion: v1
kind: Service
metadata:
  name: photo-service
spec:
  selector:
    app: photo-app
  ports:
    - port: 3000
      targetPort: 3000   # FIXED
      nodePort: 30007    # OPTIONAL but recommended
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo   # MUST match your ConfigMap hostname
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    
